### ISSUE TITLE
Version 1.0.3 or 1.0.2 very glitchy.

### ISSUE THREAD

**Issue by discord-bot-purchases** [idk-pixel/fun-util-fun-help#2]
I am on version 1.0.3 or 1.0.2. And im getting an error [cannot find a file in your thing]
please help, i love this help thing!

**Comment by idk-pixel** [comment]
Hello, I know it was very glitchy so I updated it. Please update your thing with the following command 'npm update' This command should put everything up to date in your NPM project. Thanks. Open a new issue if there is any more problems  you have,

**Comment by idk-pixel** [comment]
Heh

**Comment by idk-pixel** [comment]
#1 btw :D
